DogGo/Models/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DogGo.Models.ViewModels
{
    public class LoginViewModel
    {
        public string Email { get; set; }
    }
}

DogGo/Models/Walker.cs
using System.ComponentModel.DataAnnotations;

namespace DogGo.Models
{
    public class Walker
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Let the world know your name!")]
        [MaxLength(35)]
        public string Name { get; set; }
        [Required(ErrorMessage ="What part of town do you work in?")]

        public string Email { get; set; }
        public int NeighborhoodId { get; set; }
        public string ImageUrl { get; set; }
        public Neighborhood Neighborhood { get; set; }
    }
}

DogGo/Controllers/WalkersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using DogGo.Repositories;
using DogGo.Models;
using DogGo.Models.ViewModels;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;

namespace DogGo.Controllers
{
    public class WalkersController : Controller
    {
        private readonly IWalkerRepository _walkerRepo;
        private readonly IWalksRepository _walksRepo;
        private readonly IOwnerRepository _ownerRepo;
        private readonly INeighborhoodRepository _neighborhoodRepo;

        public WalkersController(IWalkerRepository WalkerRepository, IWalksRepository WalksRepository, IOwnerRepository ownerRepository, INeighborhoodRepository neighborhoodRepository)
        {
            _walkerRepo = WalkerRepository;
            _walksRepo = WalksRepository;
            _ownerRepo = ownerRepository;
            _neighborhoodRepo = neighborhoodRepository;
        }

        //Login action for doggo info

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(LoginViewModel viewModel)
        {
            Walker walker = _walkerRepo.GetWalkerByEmail(viewModel.Email);

            if(walker == null)
            {
                return Unauthorized();
            }

            List<Claim> claims = new List<Claim>
            {
               new Claim(ClaimTypes.NameIdentifier, walker.Id.ToString()),
               new Claim(ClaimTypes.Email, walker.Email),
               new Claim(ClaimTypes.Role, "Walker")
            };

            ClaimsIdentity claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity));

            return RedirectToAction("Details", "Walkers");
        }
        // GET: WalkersController
        //sets action of Index() so that when it is call in StartUp.cs it will show list of walkers

        //public ActionResult AssociatedWalks()
        //{

        //}
        public ActionResult Index()
        {

            if (User.IsInRole("Walker") && User.Identity.IsAuthenticated)
            {
                int id = GetCurrentWalker();
                Owner owner = _ownerRepo.GetOwnerById(id);
                List<Walker> walkers = _walkerRepo.GetWalkersInNeighborhood(owner.NeighborhoodId);
                List<Neighborhood> neighborhood = _neighborhoodRepo.GetNeighborhoodsById(owner.NeighborhoodId);

                LocalWalkerListViewModel vm = new LocalWalkerListViewModel
                {
                    Walker = walkers,
                    Neighborhoods = neighborhood
                };

                return View(vm);
            } else
            {
               List<Walker> walkers = _walkerRepo.GetAllWalkers();
               List<Neighborhood> neighborhood = _neighborhoodRepo.GetAll();

                LocalWalkerListViewModel vm = new LocalWalkerListViewModel
                {
                    Walker = walkers,
                    Neighborhoods = neighborhood
                };
                return View(vm);
            }
        }


        // GET: WalkersController/Details/5
        public ActionResult Details(int id)
        {
            int walkerId = GetCurrentWalker();

            Walker walker = _walkerRepo.GetWalkerById(walkerId);

            List<Walks> walks = _walksRepo.GetWalksByWalker(walkerId);

            WalkerProfileViewModel vm = new WalkerProfileViewModel
            {
                Walker = walker,
                Walks = walks
            };

            if (walker == null)
            {
                return NotFound();
            }
            return View(vm);
        }

        // GET: WalkersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WalkersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: WalkersController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: WalkersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: WalkersController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: WalkersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public int GetCurrentWalker()
        {        
            int id = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            return id;
        }
    }
}

DogGo/Controllers/WalksController.cs
using DogGo.Repositories;
using DogGo.Models;
using DogGo.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using System;

namespace DogGo.Controllers
{
    
    public class WalksController : Controller
    {
        private readonly IWalkerRepository _walkerRepository;
        private readonly IWalksRepository _walksRepository;
        private readonly IDogRepository _dogRepository;
        private readonly IOwnerRepository _ownerRepository;

        public WalksController(IWalksRepository walksRepository, IWalkerRepository walkerRepository, IDogRepository dogRepository, IOwnerRepository ownerRepository)
        {
            _walkerRepository = walkerRepository;
            _walksRepository = walksRepository;
            _dogRepository = dogRepository;
            _ownerRepository = ownerRepository;
        }
        // GET: WalksController
        public ActionResult Index()
        {

            return View();
        }

        // GET: WalksController/Details/5
        public ActionResult Details(int id)
        {
            List<Walks> walks = _walksRepository.GetWalkByDogId(id);
            List<Owner> owners = 
            WalksListViewModels vm = new WalksListViewModels
            
            {
                Walks = walks,


            };
                        return View(vm);
        }

        // GET: WalksController/Create
        public ActionResult Create(int id)
        {
            Walker walker = _walkerRepository.GetWalkerById(id);
            int ownerId = GetCurrentOwner();
            List<Dog> dogs = _dogRepository.GetDogsByOwnerId(ownerId);

            AppointmentViewModel avm = new AppointmentViewModel
            {
                OwnerId = ownerId,
                Walker = walker,
                Doggos = dogs
            };
            return View(avm);
        }

        // POST: WalksController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AppointmentViewModel avm, int id)
        {
            try
            {
                _walksRepository.AddWalk(avm.Walk);
                return RedirectToAction("Details", "Owners");
            }
            catch(Exception ex)
            {
                Walker walker = _walkerRepository.GetWalkerById(id);
                int ownerId = GetCurrentOwner();
                List<Dog> dogs = _dogRepository.GetDogsByOwnerId(ownerId);

                avm = new AppointmentViewModel
                {
                    OwnerId = ownerId,
                    Walker = walker,
                    Doggos = dogs,
                    ErrorMessage = "Oh no, seems something is wrong. Please ensure the form is filled out completely"
                };
                return View(avm);
            }
        }

        // GET: WalksController/Edit/5
        public ActionResult Edit(int id)
        {
            Walks walk = _walksRepository.GetWalkById(id);
            
            return View(walk);
        }

        // POST: WalksController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Walks walk)
        {

            try
            {
                _walksRepository.UpdateWalk(walk);
                return RedirectToAction("Details", "Walkers");
            }
            catch
            {
                return View();
            }
        }

        // GET: WalksController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: WalksController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public int GetCurrentOwner()
        {
            int id = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            return id;
        }
    }
}

DogGo/Views/Walkers/Details.cshtml
@model DogGo.Models.ViewModels.WalkerProfileViewModel


@{
    ViewData["Title"] = "Details";
}

<h1>Walker Profile</h1>

<div>
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="@Model.Walker.ImageUrl" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">@Model.Walker.Name</h5>
            <p class="card-text">@Model.Walker.Neighborhood.Name</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Date</th>
                            <th scope="col">Duration</th>
                            <th scope="col">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Walks walk in Model.Walks)
                        {
                        <tr>
                            <td>@walk.Date</td>
                            <td>@walk.Duration</td>
                            @if (walk.WalkStatusId == 1)
                            {
                                <td>
                                    <h5>Pending</h5>
                                </td>
                            }
                            else if (walk.WalkStatusId == 2)
                            {
                                <td>
                                    <h5>Accepted</h5>
                                </td>
                            }
                            else if (walk.WalkStatusId == 3)
                            {
                                <td>
                                    <h5>Completed!</h5>
                                </td>
                            }
                        <td>@Html.ActionLink("Update Status", "Edit", "Walks", new { id = walk.Id })</td>
                        </tr>
                        }
                    </tbody>
                    </table>
</div>
            <div class="col"> 
                <h3>Total Time</h3>
            </div>
        </div>
       
        </div>
    </div>
    <div>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Walker.Id }) |
        <a asp-action="Index">Back to List</a>
    </div>

DogGo/Views/Walkers/Index.cshtml
@model DogGo.Models.ViewModels.LocalWalkerListViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Our Loyal Walkers!</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Avatars
            </th>
            <th>
                Walker
            </th>
            <th>
                Neighborhoods
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Walker) {
        <tr>
            <td>
                <a href="/Walkers/Details/@item.Id"><img src="@item.ImageUrl" alt="Walker avatar" /></a>
            </td>

            <td>
                @item.Name
            </td>
            <td>
                @foreach (Neighborhood neighborhood in Model.Neighborhoods)
                {
                    if (neighborhood.Id == item.NeighborhoodId)
                    {
                        <p>@neighborhood.Name</p>
                    }
                }
                @*@Model.Neighborhood.Name;*@
            </td>

        </tr>
}
    </tbody>
</table>

DogGo/Views/Walkers/Login.cshtml
@model DogGo.Models.Walker

@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

<h4>Walker</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>